{% set name = "pydyf" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1764773ff01d71f941497d6dd32a21b87baf5b98f86cd47965ac33f3eb64c127

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core >=2,<4
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pydyf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.courtbouillon.org/pydyf
  summary: A low-level PDF generator.
  license: BSD-3-Clause AND AGPL-3.0-or-later
  license_file:
    - LICENSE
    - tests/LICENSE
  dev_url: https://github.com/CourtBouillon/pydyf
  doc_url: https://doc.courtbouillon.org/pydyf/

extra:
  recipe-maintainers:
    - liZe
    - BastianZim
