{% set name = "pydyf" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 06ebc18b4de29fc1450ae49dd142ecd26bd7ba09d0b1919e365fbc3d8af8a622

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - pydyf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.courtbouillon.org/pydyf
  summary: A low-level PDF generator.
  license: BSD-3-Clause
  license_file:
    - LICENSE
  dev_url: https://github.com/CourtBouillon/pydyf
  doc_url: https://doc.courtbouillon.org/pydyf/

extra:
  recipe-maintainers:
    - liZe
    - BastianZim
